apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cassandra-test
  name: cassandra-client
spec:
  ports:
  - name: cql
    port: 9042
    protocol: TCP
    targetPort: 9042
  - name: jmx
    port: 7199
    protocol: TCP
    targetPort: 7199
  selector:
    app: cassandra-test
  sessionAffinity: None
