apiVersion: v1
kind: ImageStream
metadata:
  name: redhat-openjdk-18
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
