FROM redhat-openjdk-18:latest


ENV JAVA_HOME=/usr/lib/jvm/java-1.8.0 \
    KAFKA_HOME=/opt/kafka \
    TEST_VAR2=2

COPY fix-permissions /usr/local/bin

USER root

RUN INSTALL_PKGS="gettext tar zip unzip hostname " && \
    yum install -y $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    yum clean all  && \
    mkdir -p $KAFKA_HOME && \
    curl -fsSL https://archive.apache.org/dist/kafka/${KAFKA_VERSION}/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz | tar xzf - --strip 1 -C $KAFKA_HOME/ && \
    mkdir -p $KAFKA_HOME/logs && \
    /usr/local/bin/fix-permissions $KAFKA_HOME 

WORKDIR "/opt/kafka"

EXPOSE 9092
